name: Terraform

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0
        terraform_wrapper: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Terraform Plan
      id: plan
      run: |
        ls
        cd after/terraform
        ls
        terraform init
        terraform plan -input=false -out plan
        pwd

    - name: Tag check
      id: tagcheck
      run: |
        cd after/terraform
        terraform show -json plan > plan.json
        python3 -m pip install jsonpath_ng
        python3 tag_check.py

    - name: Infracost analysis
      id: infracost
      run: |
        cd after/terraform
        curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
        infracost configure set api_key ico-pGji1tGXoD7boNip3CsIPyIxAz2zDHIY
        infracost breakdown --path .

    - name: Terraform Apply
      id: apply
      run: |
        terraform apply
        
#       terraform show -json plan | jq -r ".planned_values.root_module.child_modules[].resources[] | [.address, .values.tags, .values.tags_all]"
#    - name: Terraform Apply
#      if: github.ref == 'refs/heads/main'
#      run: terraform apply -auto-approve
